### ISSUE TITLE
Where is the link for .ova file?

### ISSUE THREAD

**Issue by Yi991107** [uwplse/szalinski#22]

**Comment by chandrakananandi** [comment]
The artifact is available on the [ACM DL](https://dl.acm.org/doi/10.1145/3385412.3386012).

**Comment by chandrakananandi** [comment]
I realized that the ACM DL doesn't contain a link to the VM image either. I have now added it to the README: https://github.com/uwplse/szalinski/blob/master/README.md under "Getting Started".
